AWSTemplateFormatVersion: "2010-09-09"
Description: "CF Template to create the s3 bucket to store the glue job code."
Parameters:
  AppCodedBucketName:
    Type: String
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref AppCodedBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  AppCodeBucketName:
    Description: The name of the bucket that has application code
    Value: !Ref S3Bucket
    Export:
      Name: AppCodeBucket